seo:
  site_name: Example
  title: Example SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/regula.aschwanden/
  facebook_url:
  pinterest_url:
  linkedin_url: https://www.linkedin.com/in/regula-aschwanden-49352923/
design:
  dark-text_color: '#3A3020'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#EBDEC7'
  medium_color: '#CFE9B9'
  light_color: '#EBDEC7'
  v-light_color: '#FFFFF1'
  featured_color: '#A38563'
  accent_color: '#a74a4a'
